library(dplyr)
library(readr)

input_values <- c(
  NA,
  "bankssts",
  "caudalmiddlefrontal",
  "fusiform",
  "inferiorparietal",
  "inferiortemporal",
  "lateraloccipital",
  "lateralorbitofrontal",
  "middletemporal",
  "parsopercularis",
  "parsorbitalis",
  "parstriangularis",
  "postcentral",
  "precentral",
  "rostralmiddlefrontal",
  "superiorfrontal",
  "superiorparietal",
  "superiortemporal",
  "supramarginal",
  "temporalpole",
  "transversetemporal",
  "insula",
  "caudalanteriorcingulate",
  "corpuscallosum",
  "cuneus",
  "entorhinal",
  "isthmuscingulate",
  "lingual",
  "medialorbitofrontal",
  "parahippocampal",
  "paracentral",
  "pericalcarine",
  "posteriorcingulate",
  "precuneus",
  "rostralanteriorcingulate",
  "frontalpole",
  "Brain Stem",
  "Corpus Callosum",
  "Corpus Callosum",
  "Corpus Callosum",
  "Corpus Callosum",
  "Corpus Callosum",
  "Cerebellum Cortex",
  "Choroid Plexus",
  "Thalamus",
  "Thalamus",
  "Ventral Diencephalon",
  "Optic Chiasm",
  "Accumbens",
  "Amygdala",
  "Caudate",
  "Hippocampus",
  "Pallidum",
  "Putamen",
  "Vessel"
)

output_values <- c(
  NA,
  "occipital neocortex",
  "dorsolateral prefrontal cortex",
  "inferolateral temporal cortex (area TEv, area 20)",
  "posteroventral (inferior) parietal cortex",
  "temporal neocortex",
  "primary visual cortex (striate cortex, area V1/17)",
  "orbital frontal cortex",
  "posterior (caudal) superior temporal cortex (area 22c)",
  "ventrolateral prefrontal cortex",
  "orbital frontal cortex",
  "ventrolateral prefrontal cortex",
  "primary somatosensory cortex (area S1, areas 3,1,2)",
  "primary motor cortex (area M1, area 4)",
  "dorsolateral prefrontal cortex",
  "anterior (rostral) cingulate (medial prefrontal) cortex",
  "parietal neocortex",
  "temporal neocortex",
  "posteroventral (inferior) parietal cortex",
  "amygdaloid complex",
  "primary auditory cortex (core)",
  "striatum",
  "anterior (rostral) cingulate (medial prefrontal) cortex",
  "cerebellum",
  "primary visual cortex (striate cortex, area V1/17)",
  "hippocampus (hippocampal formation)",
  "mediodorsal nucleus of thalamus",
  "primary visual cortex (striate cortex, area V1/17)",
  "orbital frontal cortex",
  "hippocampus (hippocampal formation)",
  "primary motor-sensory cortex (samples)",
  "primary visual cortex (striate cortex, area V1/17)",
  "mediodorsal nucleus of thalamus",
  "parietal neocortex",
  "anterior (rostral) cingulate (medial prefrontal) cortex",
  "frontal pole",
  NA,                                       
  NA,                                   
  NA,                                        
  NA,                                       
  NA,                                        
  NA,                                        
  "cerebellum",                              
  NA,                                        
  "dorsal thalamus",
  "dorsal thalamus",                                  
  NA,                                        
  NA,                                         
  "striatum",                                
  "amygdaloid complex",                       
  "striatum",                                 
  "hippocampus (hippocampal formation)",     
  NA,                                        
  "striatum",                                 
  NA                                          
)

output_values_macro <- c(
  NA, 
  "lobo temporal", 
  "lobo frontal", 
  "lobo temporal",
  "lobo parietal",
  "lobo temporal",
  "lobo occipital",
  "lobo frontal",
  "lobo temporal",
  "lobo frontal",
  "lobo frontal",
  "lobo frontal",
  "lobo frontal",
  "lobo frontal",
  "lobo frontal",
  "lobo frontal",
  "lobo parietal",
  "lobo temporal",
  "lobo parietal",
  "lobo temporal",
  "lobo temporal",
  "lobo temporal",
  "lobo frontal",
  "lobo frontal",
  "lobo occipital",
  "lobo temporal",
  "lobo parietal",
  "lobo temporal",
  "lobo frontal",
  "lobo temporal",
  "lobo frontal",
  "lobo occipital",
  "lobo frontal",
  "lobo parietal",
  "lobo frontal",
  "lobo frontal",
  NA,                                        
  NA,                                       
  NA,                                        
  NA,                                        
  NA,                                        
  NA,                                       
  "cerebelo", 
  NA,                                        
  "subcortical",
  "subcortical",                                                      
  NA,                                        
  NA,                                        
  "subcortical",                             
  "lobo temporal",                           
  "subcortical",                           
  "lobo temporal",                            
  NA,                                         
  "subcortical",                            
  NA
)

mapeamento <- data.frame(
  region = input_values,
  structure_name = output_values,
  macro_regions = output_values_macro,
  stringsAsFactors = FALSE
)

write_csv(mapeamento, "mapeamento_regioes.csv")